[package]
name = "api-doc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = "4.5"
dotenv = "0.15.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
config = "0.15"
